### PR TITLE
Add script for verifying links

### PR DESCRIPTION
**Pull request by simeg**
Background: https://github.com/agarrharr/awesome-cli-apps/issues/185

**TODO:**
- [x] Create Travis project and configure it to run once every 24h (or whatever value you think is good) (@agarrharr)
- [x] Add appropriate Travis file (@simeg)

Ping @agarrharr

### CODE REVIEW

**Comment by simeg** [comment]
Ping @agarrharr.

**Comment by agarrharr** [comment]
Thanks for the reminder. 👍 I went ahead and merged it and I'm currently working on setting up Travis.

**Comment by simeg** [comment]
Nice! It's real simple, I used [this resource](https://docs.travis-ci.com/user/cron-jobs/) to do it. Don't forget to add a badge to the original repo, or if you prefer to receive e-mails from Travis you can configure that too.

**Comment by agarrharr** [comment]
I got this:

screen shot 2018-06-21 at 1 09 40 pm

**Comment by simeg** [comment]
See #2.

**Pull request merged**
